---
title: 15. 异常
description: 
published: true
date: 2021-03-14T05:45:58.593Z
tags: 
editor: markdown
dateCreated: 2021-03-13T01:50:14.574Z
---

# 异常

当检测到⼀个错误时，解释器就⽆法继续执⾏了，反⽽出现了⼀些错误的提示，这就是所谓的"异常"。

例如：以 r ⽅式打开⼀个不存在的⽂件。

```python
open('test.txt','r')
```

输出：

```python
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-7-910a3254b64c> in <module>
----> 1 open('test.txt','r')

FileNotFoundError: [Errno 2] No such file or directory: 'test.txt'
```

而有些时候我们并不想因为异常而终止程序，由此就需要编写异常处理方法，通常使用手段是把异常信息保存在日志中。

# 异常处理

下面以整型输入为例：

```python
>>> while True:
...     try:
...         x = int(input("Please enter a number: "))
...         break
...     except ValueError:
...         print("Oops!  That was no valid number.  Try again...")
...
```

工作原理：

1. 首先，执行 `try` 子句。
2. 如果没有异常发生，则跳过 `except` 子句并完成`try`语句的执行。
3. 如果在执行 `try` 子句时发生了异常，则跳过该子句中剩下的部分。然后，如果异常的类型和 `except`关键字后面的异常匹配，则执行 `except` 子句
4. 如果发生的异常和 `except` 子句中指定的异常不匹配，则将其传递到外部的`try`语句中

> 注意：如果尝试执⾏的代码的异常类型和要捕获的异常类型不⼀致，则⽆法捕获异常。
{.is-warning}

## try-except

一个 `try`语句可能有多个 `except` 子句，以指定不同异常的处理程序

```python
... except (RuntimeError, TypeError, NameError):
...     pass
```

也可以在 `except` 子句可以在异常名称后面指定一个变量。这个变量和一个异常实例绑定，它的参数存储在 `instance.args` 中

```python
>>> try:
...     raise Exception('spam', 'eggs')
... except Exception as inst:
...     print(type(inst))    # the exception instance
...     print(inst.args)     # arguments stored in .args
...     print(inst)          # __str__ allows args to be printed directly,
...                          # but may be overridden in exception subclasses
...     x, y = inst.args     # unpack args
...     print('x =', x)
...     print('y =', y)
...
<class 'Exception'>
('spam', 'eggs')
('spam', 'eggs')
x = spam
y = eggs
```

## else

其次，`try...except`语句有一个可选的 else 子句，在使用时必须放在所有的 except 子句后面

```python
for arg in sys.argv[1:]:
    try:
        f = open(arg, 'r')
    except OSError:
        print('cannot open', arg)
    else:
        print(arg, 'has', len(f.readlines()), 'lines')
        f.close()
```

## finally

- 如果存在`finally`子句，则 `finally` 子句将作为`try`语句结束前的最后一项任务被执行。 `finally` 子句不论 `try` 语句是否产生了异常都会被执行

- 如果在执行 `try` 语句时遇到一个`break`, `continue`或 `return`语句，则 `finally` 子句将在执行 `break`, `continue` 或 `return` 语句之前被执行。

- 如果 `finally` 子句中包含一个 `return` 语句，则返回值将来自 `finally` 子句的某个 `return` 语句的返回值，而非来自 `try` 子句的 `return` 语句的返回值。

```python
def f():
    try:
        print("try")
        return "try" 
    finally:
        print("finally")
        return "finally"
>>> try
>>> finally
>>> res: finally
```

> 在实际应用程序中，`finally`子句对于释放外部资源（例如文件或者网络连接）非常有用，无论是否成功使用资源。
{.is-info}


# 抛出异常

`raise` 语句支持强制触发指定的异常。唯一的参数就是要触发的异常。这个参数必须是异常实例或异常类（派生自 [`Exception`](https://docs.python.org/zh-cn/3/library/exceptions.html#Exception) 的类）例如：

```python
>>> raise NameError('HiThere')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: HiThere
```

# ⾃定义异常

自定义异常通常应该直接或间接地从`Exception`类派生。

```python
class Error(Exception):
    """Base class for exceptions in this module."""
    pass

class InputError(Error):
    """Exception raised for errors in the input.

    Attributes:
        expression -- input expression in which the error occurred
        message -- explanation of the error
    """

    def __init__(self, expression, message):
        self.expression = expression
        self.message = message
```

例如：

```python
# ⾃定义异常类，继承Exception
class ShortInputError(Exception):
    def __init__(self, length, min_len):
        self.length = length
        self.min_len = min_len

    # 设置抛出异常的描述信息
    def __str__(self):
        
        return f'你输⼊的⻓度是{self.length}, 不能少于{self.min_len}个字符'
    
def main():
    try:
        con = input('请输⼊密码： ')
        if len(con) < 3:
            raise ShortInputError(len(con), 3)
    except Exception as result:
        print(result)
    else:
        print('密码已经输⼊完成')

main()
```
